{
 "title": "OPC UA FX",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latenza Media",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\") \n\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\") \n\n  |> filter(fn: (r) => r[\"_field\"] == \"Latency_ms\") \n\n  |> mean()  // Calcola la media di TUTTI i punti \n\n  |> yield(name: \"Latenza Media\") "
    }
   ]
  },
  {
   "title": "Jitter Medio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\") \n\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\") \n\n  |> filter(fn: (r) => r[\"_field\"] == \"Latency_ms\") \n\n  |> aggregateWindow(every: 1s, fn: stddev, createEmpty: false) // Calcola Jitter al secondo \n\n  |> mean() // Fai la media di tutti i Jitter \n\n  |> yield(name: \"Jitter Medio\") "
    }
   ]
  },
  {
   "title": "Latenza",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Latency_ms\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \r\n  |> yield(name: \"Latenza Media\") "
    }
   ]
  },
  {
   "title": "Packet Delay Variation (PDV) Medio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\") \r\n\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\") \r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Latency_ms\") \r\n\r\n  |> aggregateWindow(every: 1s, fn: stddev, createEmpty: false) \r\n\r\n  |> yield(name: \"Jitter (ms)\") "
    }
   ]
  },
  {
   "title": "Joint Position",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"JointPosition\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Posizione\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Vibration\")\r\n  // Qui usiamo MAX per vedere i picchi di vibrazione, non la media appiattita\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Vibrazione (Max)\")"
    }
   ]
  },
  {
   "title": "Velocita",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\n  |> range(start: -10s) // Guardiamo solo gli ultimi 10 secondi\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> last() "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\n  |> range(start: -10s) // Guardiamo solo gli ultimi 10 secondi\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"JointPosition\")\n  |> last() "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\n  |> range(start: -9999999s) // Guardiamo solo gli ultimi 10 secondi\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage\")\n  |> last() //"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"tesi_tsn\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misurazioni_fx\")\n  // Qui il trucco: usiamo \"or\" per prenderli entrambi\n  |> filter(fn: (r) => r[\"_field\"] == \"JointPosition\" or r[\"_field\"] == \"Vibration\")\n  |> aggregateWindow(every: 50ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}